# Generated by Django 2.2.5 on 2020-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verifier',
            field=models.BooleanField(default=False, verbose_name='verifier status'),
        ),
    ]
