# Generated by Django 2.2.5 on 2020-01-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_login_reg', '0003_verifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verifier',
        ),
    ]
