# Generated by Django 2.2.5 on 2020-01-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_reg', '0004_delete_verifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
