# Generated by Django 2.2.5 on 2020-01-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_reg', '0005_verifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifier',
            old_name='user',
            new_name='username',
        ),
    ]
