# Generated by Django 3.0 on 2020-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_reg', '0006_auto_20200130_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seatallo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glce', models.IntegerField(default=None, null=True)),
                ('capce', models.IntegerField(default=None, null=True)),
                ('ilsce', models.IntegerField(default=None, null=True)),
                ('nrice', models.IntegerField(default=None, null=True)),
                ('ciwgcce', models.IntegerField(default=None, null=True)),
                ('pioce', models.IntegerField(default=None, null=True)),
                ('fnce', models.IntegerField(default=None, null=True)),
                ('glee', models.IntegerField(default=None, null=True)),
                ('capee', models.IntegerField(default=None, null=True)),
                ('ilsee', models.IntegerField(default=None, null=True)),
                ('nriee', models.IntegerField(default=None, null=True)),
                ('ciwgcee', models.IntegerField(default=None, null=True)),
                ('pioee', models.IntegerField(default=None, null=True)),
                ('fnee', models.IntegerField(default=None, null=True)),
                ('glete', models.IntegerField(default=None, null=True)),
                ('capete', models.IntegerField(default=None, null=True)),
                ('ilsete', models.IntegerField(default=None, null=True)),
                ('nriete', models.IntegerField(default=None, null=True)),
                ('ciwgcete', models.IntegerField(default=None, null=True)),
                ('pioete', models.IntegerField(default=None, null=True)),
                ('fnete', models.IntegerField(default=None, null=True)),
                ('glit', models.IntegerField(default=None, null=True)),
                ('capit', models.IntegerField(default=None, null=True)),
                ('ilsit', models.IntegerField(default=None, null=True)),
                ('nriit', models.IntegerField(default=None, null=True)),
                ('ciwgcit', models.IntegerField(default=None, null=True)),
                ('pioit', models.IntegerField(default=None, null=True)),
                ('fnit', models.IntegerField(default=None, null=True)),
                ('glme', models.IntegerField(default=None, null=True)),
                ('capme', models.IntegerField(default=None, null=True)),
                ('ilsme', models.IntegerField(default=None, null=True)),
                ('nrime', models.IntegerField(default=None, null=True)),
                ('ciwgcme', models.IntegerField(default=None, null=True)),
                ('piome', models.IntegerField(default=None, null=True)),
                ('fnme', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
